language: rust
rust:
  - 1.45.0
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo test --bin node test -- --nocapture --test-threads=1
